apiVersion: v1
kind: Service
metadata:
  name: auto-trader-view-vehicles-service
  namespace: app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: auto-trader-view-vehicles-deployment
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8082
    targetPort: 8080
    